<?php

namespace Tests\Unit\Annotation;

use Tests\TestCase;

class BeforeAfterTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
//        var_dump('setUp');
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
//        var_dump('tearDown');
    }
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testExample()
    {
        $this->assertTrue(true);
//        var_dump('testExample');
    }

    /**
     * Function run before test.
     * @before
     */
    public function runBeforeTest()
    {
//        var_dump('before');
    }

    /**
     * Function run after test.
     * @after
     */
    public function runAfterTest()
    {
//        var_dump('after');
    }
}
